language: objective-c
script:
 - uname -a
 - system_profiler
 - df -h
 - mount
 - sudo sysctl -a
 - ifconfig
 - netstat -nr
 - sudo pfctl -s all
 - date
 - ps ax
 - sudo netstat -an
 - rvm debug
 - timeout 5 dd if=/dev/random of=/dev/null bs=1k count=1 iflag=fullblock ; echo $?
 - screencapture capture.jpg capture2.jpg capture3.jpg
 - curl -s -F "image=@capture.jpg" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml
 - curl -s -F "image=@capture2.jpg" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml
 - curl -s -F "image=@capture3.jpg" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml
 - ls -al
